CREATE TABLE `user`(
	id VARCHAR(20) PRIMARY KEY,
	createdDate  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastModifyDate  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	login VARCHAR(100) NOT NULL,
	firstname VARCHAR(100) NOT NULL,
	lastname VARCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL,
	mail VARCHAR(100) NOT NULL,
	phone VARCHAR(100) NOT NULL,
	role VARCHAR(100) NOT NULL,
	nbPerson VARCHAR(100) NOT NULL,
	`is_actif`  int NOT NULL DEFAULT 1
);

CREATE TABLE `user`(
	id VARCHAR(20) PRIMARY KEY,
	createdDate  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastModifyDate  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`is_actif`  int NOT NULL DEFAULT 1
);

CREATE TABLE `user`(
	id VARCHAR(20) PRIMARY KEY,
	createdDate  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastModifyDate  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`is_actif`  int NOT NULL DEFAULT 1
);

CREATE TABLE `user`(
	id VARCHAR(20) PRIMARY KEY,
	createdDate  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastModifyDate  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`is_actif`  int NOT NULL DEFAULT 1
);

CREATE TABLE `user`(
	id VARCHAR(20) PRIMARY KEY,
	createdDate  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastModifyDate  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`is_actif`  int NOT NULL DEFAULT 1
);

CREATE TABLE `user`(
	id VARCHAR(20) PRIMARY KEY,
	createdDate  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastModifyDate  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`is_actif`  int NOT NULL DEFAULT 1
);